'use client';
import {useEffect,useId,useRef,useState} from 'react';
const heights=[1250,850,1400,1150,1400,900,1350,950,1200,1400,1000,1350];
const sources=new Map<string,Promise<string>>();
function source(url:string){let promise=sources.get(url);if(!promise){promise=fetch(url).then(r=>{if(!r.ok)throw new Error('Artwork unavailable');return r.text()});sources.set(url,promise);promise.catch(()=>sources.delete(url))}return promise}
export default function Artwork({index,alt,className='',paused=false,priority=false}:{index:number;alt:string;className?:string;paused?:boolean;priority?:boolean}){
 const ref=useRef<HTMLDivElement>(null),id=useId().replace(/[^a-zA-Z0-9]/g,'');const[visible,setVisible]=useState(false),[reduced,setReduced]=useState(true),[foreground,setForeground]=useState(true),[svg,setSvg]=useState('');const url='/art/'+String(index).padStart(2,'0')+'.svg';
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(media.matches);change();media.addEventListener('change',change);const visibility=()=>setForeground(!document.hidden);visibility();document.addEventListener('visibilitychange',visibility);const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting&&entry.intersectionRatio>0.001),{threshold:[0,0.001]});if(ref.current)observer.observe(ref.current);return()=>{observer.disconnect();media.removeEventListener('change',change);document.removeEventListener('visibilitychange',visibility)}},[]);
 useEffect(()=>{if(!visible||reduced||svg)return;let alive=true;source(url).then(text=>{if(!alive)return;const doc=new DOMParser().parseFromString(text,'image/svg+xml');const root=doc.documentElement;root.setAttribute('aria-hidden','true');root.setAttribute('focusable','false');root.setAttribute('preserveAspectRatio',className.includes('hero-art')?'xMidYMid meet':'xMidYMid slice');root.querySelectorAll('[id]').forEach(el=>{const original=el.id;el.id=id+'-'+original;root.querySelectorAll('[fill],[stroke]').forEach(target=>{for(const attr of ['fill','stroke'])if(target.getAttribute(attr)==='url(#'+original+')')target.setAttribute(attr,'url(#'+id+'-'+original+')')})});root.querySelectorAll('path').forEach((path,i)=>{path.setAttribute('class','living-contour');path.setAttribute('style',`--contour-delay:${-(i/169)*1.5-index*1.3}s;--contour-duration:${26+(index%5)*3}s;transform-origin:500px ${heights[index-1]/2}px`)});setSvg(new XMLSerializer().serializeToString(root))}).catch(()=>{/* The original image remains available if enhancement fails. */});return()=>{alive=false}},[visible,reduced,url,id,index,svg,className]);
 return <div ref={ref} className={'artwork '+className} data-running={visible&&!reduced&&foreground&&!paused?'true':'false'} data-enhanced={svg&&!reduced?'true':'false'} style={{aspectRatio:`1000 / ${heights[index-1]}`}} role="img" aria-label={alt}><img src={url} alt="" aria-hidden="true" loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined}/>{svg&&!reduced&&<div className="living-svg" dangerouslySetInnerHTML={{__html:svg}}/>}</div>
}
