'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import Artwork from './artwork';
const titles=['N°12 — Dérive','N°07 — Seuil','N°03 — Étreinte','N°09 — Ressac','N°04 — Latence','N°11 — Sillage','N°02 — Repli','N°08 — Affleurement','N°06 — Suspension','N°01 — Lisière','N°10 — Rémanence','N°05 — Écho'];
const links=[['Galerie','galerie'],["L’artiste",'artiste'],['Dérives','derives'],['Expositions','expositions'],['Écrire','contact']];
export default function Home(){const[menu,setMenu]=useState(false);const cursor=useRef<HTMLDivElement>(null),entry=useRef<HTMLParagraphElement>(null);useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const move=(e:PointerEvent)=>{if(cursor.current){cursor.current.style.left=e.clientX+'px';cursor.current.style.top=e.clientY+'px';cursor.current.style.opacity='1'}};const leave=()=>{if(cursor.current)cursor.current.style.opacity='0'};const scroll=()=>{if(entry.current)entry.current.style.opacity=String(Math.max(0,1-window.scrollY/200))};if(!reduced)window.addEventListener('pointermove',move);document.addEventListener('pointerleave',leave);window.addEventListener('scroll',scroll,{passive:true});return()=>{window.removeEventListener('pointermove',move);document.removeEventListener('pointerleave',leave);window.removeEventListener('scroll',scroll)}},[]);return <><div ref={cursor} className="cursor" aria-hidden="true"/><a className="skip" href="#main">Voir la galerie</a><header><a className="wordmark" href="#">Liora Venn</a><Button className="menu-trigger" variant="ghost" onClick={()=>setMenu(true)} aria-label="Ouvrir le menu"><span/><span/></Button></header><main id="main"><section className="hero"><Artwork className="hero-art" index={1} alt="Forme organique plissée, nacre et cuivre sur fond noir" priority paused={menu}/><div className="hero-vignette"/><div className="hero-title"><h1>Liora Venn</h1><p>Studio. Marseille.</p></div><p ref={entry} className="invitation">Entrer dans l'œuvre.</p><a href="#galerie" className="gallery-cta">Voir la galerie <span aria-hidden="true">↓</span></a></section>
<section id="galerie" className="gallery"><p className="gallery-intro">Chaque pièce est une porte.</p><div className="masonry">{titles.map((title,i)=><figure key={title} className={'art art-'+i} tabIndex={0} aria-label={title}><img src={'/art/'+String(i+1).padStart(2,'0')+'.svg'} alt={title} loading="lazy"/><figcaption>{title}</figcaption></figure>)}</div></section>
<section id="artiste" className="artist"><div className="artist-art"><Artwork index={8} alt="N°08 — Affleurement" paused={menu}/></div><div className="artist-copy"><h2>Liora Venn</h2><p>Liora Venn travaille les formes organiques et la couleur comme une matière à part entière. Basée à Marseille, elle expose depuis plusieurs années dans des galeries indépendantes, en France et à l'étranger. Son travail explore la frontière entre figuration et abstraction. Jamais l'une sans l'autre.</p></div></section>
<section id="derives" className="series"><div className="series-heading"><h2>Dérives</h2><div><p>Une série sur le mouvement empêché : ce qui reste quand on ne peut plus avancer.</p><p className="technical">Acrylique et encre sur toile. 2025–2026.</p></div></div><div className="series-images"><img src="/art/03.svg" alt="N°03 — Étreinte" loading="lazy"/><img src="/art/09.svg" alt="N°06 — Suspension" loading="lazy"/></div></section>
<section id="expositions" className="exhibitions"><ul><li>2026 — Galerie du Sud, Marseille (solo)</li><li>2025 — Nuit des Ateliers, Marseille (collective)</li><li>2024 — Espace K, Lyon (collective)</li></ul></section>
<section id="contact" className="contact"><h2>Écrire</h2><p>Pour une acquisition, une exposition, ou simplement échanger sur le travail.</p><a className="contact-link" href="mailto:?subject=Liora%20Venn%20Studio">Contacter le studio <span aria-hidden="true">↗</span></a></section></main><footer>Concept créé par Megahana — marque fictive à des fins de démonstration.</footer><Dialog open={menu} onOpenChange={setMenu}><DialogContent className="full-menu" showCloseButton={false}><DialogTitle className="sr-only">Liora Venn</DialogTitle><DialogDescription className="sr-only">Studio. Marseille.</DialogDescription><DialogClose className="close-menu" aria-label="Fermer le menu"><span/><span/></DialogClose><nav aria-label="Navigation principale">{links.map(([name,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{name}</a>)}</nav><p>Studio. Marseille.</p></DialogContent></Dialog></>}
